# Generated by Django 5.0.6 on 2024-05-26 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutoring", "0003_alter_session_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="session",
            name="time",
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
